-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSuzFsNAnWI94aa9h
OOsS7hGRHB+1EuwVhcN9BnxTTFWgCgYIKoZIzj0DAQehRANCAATwmYa0j78Wjh6S
M6ZxqHLi8TmOhL8UkVGmnlXpsHsamxPr/360fGFxaQXhySEIfKrYMO5DY+kFWj4H
Dsz9gQTt
-----END PRIVATE KEY-----